version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      APP_NAME: echo_boilerplate
      PORT: 3000
      JAEGER_SERVICE_NAME: echo-boilerplate
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI
      - "6831:6831/udp"
